version: '3.8'

services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:v0.108.0-b.80
    restart: unless-stopped
    network_mode: host # Lets AdGuard see real Client IPs and manage DHCP - doesn't use Docker's network
    cap_drop: # Reduce container privileges
      - ALL
    cap_add:
      - NET_BIND_SERVICE  # Bind port 53/80/443
      - NET_ADMIN         # Required for DHCP interface manipulation
      - NET_RAW           # Required for DHCP raw sockets and ICMP pings
    read_only: true # Read-only root filesystem
    tmpfs:
      - /tmp
      - /run
    security_opt:
      - no-new-privileges:true
    privileged: false # Make sure AdGuard cannot escalate or read the host filesystem
    volumes:
      - /srv/adguard/conf:/opt/adguardhome/conf
      - /srv/adguard/work:/opt/adguardhome/work
    labels:
      - "wud.tag.include=^v\\d+\\.\\d+\\.\\d+$"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
