# Good example
# https://raw.githubusercontent.com/nicolargo/glances/master/conf/glances.conf

[influxdb2]
host=influxdb
port=8086
org=homelab
bucket=glances
token=${GLANCES_INFLUX_TOKEN}
protocol = http


[alert]
disable=False
# Maximum number of events to display (default is 10 events)
max_events=10
# Minimum duration for an event to be taken into account (default is 6 seconds)
min_duration=10
# Minimum time between two events of the same type (default is 6 seconds)
# This is used to avoid too many alerts for the same event
# Events will be merged
min_interval=6

[diskio]
hide=sr0,zram0,loop.*
# hide=sda1,mmcblk0p.*,nvme0n1p.*,loop.*

[fs]
# allow=nfs4,nfs
# alias=/hostfs/mnt/nas:NAS,/hostfs:OS,/hostfs/mnt/appdata:Docker-Data
hide=/hostfs/mnt/nas,/hostfs/mnt/logs,/hostfs/mnt/pool,/hostfs/proc/fs/nfsd,/hostfs/srv,/hostfs/var/lib/docker,/hostfs/data,/hostfs/var/lib/containerd,/etc/resolv.conf,/etc/hostname,/etc/hosts,/etc/glances/glances.conf,/root/.config/glances/glances.pwd

[network]
hide=lo,docker0

[cpu]
disable=False

[mem]
disable=False

# Try disabling process list for speed
[processlist]
disable=True

[processcount]
disable=True
