services:
  portainer:
    image: portainer/portainer-ce:2.38.0
    container_name: portainer
    restart: unless-stopped
    # To acess via https://IP:9443 if Caddy dies.
    ports:
      - "127.0.0.1:9443:9443"
      - "192.168.50.95:9443:9443"
    environment:
      - TRUSTED_ORIGINS=${PORTAINER_DOMAIN:-portainer.example.com}
    expose:
      - 9443
    networks:
      - caddy_public
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv:/srv:ro
    read_only: true
    labels:
      - "wud.tag.include=^\\d+\\.\\d+\\.\\d+$"
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'


volumes:
  portainer_data:
    external: true

networks:
  caddy_public:
    external: true
