[global]
   netbios name = homelab
   workgroup = WORKGROUP
   server string = Homelab Samba Server
   # name resolve order = bcast host
   # multicast dns register = yes

   interfaces = lo ens18
   bind interfaces only = yes

   server min protocol = SMB3
   smb encrypt = required
   security = user
   map to guest = never
   log level = 2

[main]
   path = /mnt/pool
   browseable = yes
   writable = yes
   guest ok = no
   valid users = k
   create mask = 0755
   directory mask = 0755
   dos filemode = yes

# [public]
#    path = /shares/Shared
#    browsable = yes
#    read only = no
#    guest ok = no
#    valid users = k