version: '3.8'

services:
  whatsupdocker:
    image: getwud/wud:latest
    container_name: whats-up-docker
    restart: unless-stopped
    ports:
      - 3001:3001
    # networks:
    #   - caddy_private
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:mode=1777,size=64M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - wud_store:/store
    # env_file:
    #   - ${WUD_TELEGRAM_ENV_PATH:-/srv/whats-up-docker/telegram_unused.env} # Unused old telegram key
    environment:
      - WUD_LOG_LEVEL=INFO
      - WUD_SERVER_PORT=3001
      # - WUD_WATCHER_LOCAL_CRON=0 * * * * # Optional: Checks every hour (Default is varies)
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M

volumes:
  wud_store:

# networks:
#   caddy_private:
#     external: true