version: "3.9"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:0.9.2
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3002:8080"
    # networks:
    #   - caddy_public
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_URL=https://${OPENWEBUI_DOMAIN:-ai.example.com}
      - WEBUI_AUTH=true # enable login system
      # - LMSTUDIO_API_BASE=http://192.168.50.39:1234/v1  # replace with your GPU PC IP + LM Studio port
      - ENABLE_OPENAI_API=true
      - ENABLE_API_KEYS=true
      - DOCS_DIR=/data/docs
    cap_drop:
      - ALL
    cap_add:
      # - CHOWN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - openwebui_data:/app/backend/data
    labels:
      - "wud.tag.include=^\\d+\\.\\d+\\.\\d+$" # For What's Up Docker
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 512M


volumes:
  openwebui_data:


# networks:
#   caddy_public:
#     external: true