version: '3.8'

services:
  filestash:
    image: ugeek/filestash:armhf
    container_name: filestash
    # ports:
    #   - "8334:8334"
    expose:
      - "8334"
    networks:
      - caddy_shared
    user: "1000:1000"
    environment:
      - FILESTASH_BASE=subdomain.example.com/filestash
      - APPLICATION_URL=subdomain.example.com/filestash
    volumes:
      - /srv/filestash/config:/config  # Persist config/settings
      - /mnt/pool/Shared:/data 
    restart: unless-stopped