version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    expose:
      - "9090"
    volumes:
      - /srv/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - caddy_private


networks:
  caddy_private:
    external: true

volumes:
  prometheus-data: