version: '3.8'

services: 
  syncthing:
    image: syncthing/syncthing:2.0.14
    container_name: syncthing
    hostname: homelab
    ports:
      - 192.168.50.95:8384:8384
      - 127.0.0.1:22000:22000/tcp # Sync TCP
      - 192.168.50.95:22000:22000/tcp # Sync TCP
      - 127.0.0.1:22000:22000/udp # Sync UDP (QUIC)
      - 192.168.50.95:22000:22000/udp # Sync UDP (QUIC)
      - 127.0.0.1:21027:21027/udp # Discovery
      - 192.168.50.95:21027:21027/udp # Discovery
    # networks:
    #  - caddy_public
    environment:
      - PUID=1000
      - PGID=1000
      - STGUIADDRESS=0.0.0.0:8384 # For accessing web interface over LAN
    security_opt:
      - no-new-privileges:true
    volumes:
      - /srv/syncthing/config:/var/syncthing/config
      - /mnt/nas/Downloads:/var/syncthing/downloads
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M


# networks:
#   caddy_public:
#     external: true